///////////////////////////////////////////////////////////
//  ContactManager.cs
//  Implementation of the Class ContactManager
//  Generated by Enterprise Architect
//  Created on:      28-Nov-2017 19:06:39
//  Original author: Terrence Knoesen
///////////////////////////////////////////////////////////




using caseman.busmodel.contacts;
using caseman.datamodel;
using System;
using System.Data.Odbc;
using log4net;
namespace caseman.busmodel.contacts {

    /// <summary>
    /// This class is responsible for persisting, retrieving and deleting contacts from
    /// the BackingStore.
    /// </summary>
    public class ContactManager {
        /// <summary>
        /// This the Log4Net logger for this class.
        /// </summary>
        private readonly ILog mobjLog = LogManager.GetLogger(typeof(ContactManager));


        public ContactManager(){
            string strMess = null;
            mobjLog.Debug("Enter");




            mobjLog.Debug("Exit");
        }

		~ContactManager(){

		}

		/// <summary>
		/// Loads and returns a Contact from the BackingStore for a given ContactID.
		/// </summary>
		/// <param name="lngContactID">This the the unique identity of the Contact to load.
		/// </param>
		public Contact LoadContact(long lngContactID){
            string strMess = null;
            mobjLog.Debug("Enter");

            Contact objContact = null;




            mobjLog.Debug("Exit");


            return objContact;
		}

	}//end ContactManager

}//end namespace contacts