--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 8.0.860
--   Created On : Wednesday, 09 August, 2017 
--   DBMS       : MySql 
--   -------------------------------------------------- 

USE CaseManager
;

SET FOREIGN_KEY_CHECKS=0;


--  Drop Tables, Stored Procedures and Views 

DROP TABLE IF EXISTS tblContact
;
DROP TABLE IF EXISTS tblContactAttribute
;
DROP TABLE IF EXISTS tblContactLinkAttribute
;

--  Create Tables 
CREATE TABLE tblContact
(
	ContactID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'This is the unique identity of the Contact.',
	Title VARCHAR(50) COMMENT 'This is the title of the contact and should contain thinks like mr, mrs, miss etc...',
	Firstname VARCHAR(100) COMMENT 'This is the first name of the contact.',
	LastName VARCHAR(100) COMMENT 'This is the last name for this contact.',
	PreferredName VARCHAR(100) COMMENT 'This is the contact''s preferred name for use in email and telephone conversations.',
	OffsetUTC TINYINT NOT NULL DEFAULT 0 COMMENT 'This is the UTC time offset for this contact.',
	PRIMARY KEY (ContactID),
	UNIQUE UQ_tblContact_ContactID(ContactID)
) 
;


CREATE TABLE tblContactAttribute
(
	ContactAttributeID BIGINT NOT NULL COMMENT 'This is the unique identity for a ContactAttribute entry',
	Value VARCHAR(500) NOT NULL COMMENT 'This is the column that holds the information to be associated with the ContactAttribute',
	ContactAttributeType TINYINT NOT NULL COMMENT 'This is an enumerated value for the type of this attribute.',
	PRIMARY KEY (ContactAttributeID),
	UNIQUE UQ_tblContactAttribute_ContactAttributeID(ContactAttributeID)
) 
;


CREATE TABLE tblContactLinkAttribute
(
	ContactID BIGINT NOT NULL COMMENT 'The unique identity of the contact to which this attribute will be assigned.',
	ContactAttributeID BIGINT NOT NULL COMMENT 'This is the unique identity of the attribute that will be assigned to a contact.'
) 
;



SET FOREIGN_KEY_CHECKS=1;
